### ISSUE TITLE
Open File Manager hangs

### ISSUE THREAD

**Issue by ckingdon** [CSTARS/ecosis-data-tool#6]
On linux64 version, clicking "Open File Manger" never opens my file manager. It hangs with a spinning wheel and the word "Importing ..." beside it. I can close the dialog, but if I leave it spinning then nothing ever happens.

Strangely, if I click "Export", then "Save To" (though I have no dataset to save since the file manager doesn't happen) then I can pick a folder to save to.

**Comment by jrmerz** [comment]
It was a bad build.  I have fixed and pushed a new build.  Go ahead an re-download, should work.
